### ISSUE TITLE
What do the three buttons do?

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/desktop-wallet#64]
<img width="986" alt="screenshot 2018-12-05 12 14 32" src="https://user-images.githubusercontent.com/5106444/49487793-609d6000-f887-11e8-9d2f-89a5d287027d.png">

**Comment by Kapilbindal1** [comment]
We have updated the name of header buttons. Please see the attached screenshot.
![screen shot 2018-12-05 at 5 15 37 pm](https://user-images.githubusercontent.com/12563571/49512237-4ed1b200-f8b3-11e8-95ae-8dd57e544566.png)
