### ISSUE TITLE
"I have written down the phrase" does not work

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/desktop-wallet#69]
Clicking on "Next" does not work.

<img width="990" alt="screenshot 2018-12-05 12 29 46" src="https://user-images.githubusercontent.com/5106444/49488341-93e0ee80-f889-11e8-8478-c71993bf2b97.png">

**Comment by Kapilbindal1** [comment]
@MKong You have to click on "Click Here To Reveal Secret Words", to reveal the secret code first.
